<p>A verification report has been generated based on the selected criteria.<br><br>
<b>Report ID:</b> {{ report_id }}<br>
<b>Status Filter:</b> {{ status_filter }}<br>
<b>Report Format:</b> {{ report_format }}<br>
<b>Branch / HO:</b> {{ branch__ho }}<br>
<b>Date Range:</b> {{ date_range }}<br>
<b>Generated By:</b> {{ generated_by }}<br><br></p>

<p><b>Department Response Summary:</b><br>
{{ department_response_log }}<br><br></p>

<p>Please review the report for verification findings and further action.</p>
